import type { MinistryCategory } from "../types";
import { getSanityWriteClient } from "../client";
import { paragraphsToBlocks } from "./portableText";

export type MinistrySeed = {
  _id: string;
  slug: string;
  title: string;
  category: MinistryCategory;
  summary: string;
  paragraphs: string[];
  canonicalPath?: string;
  scheduleLabel?: string;
  scheduleDetails?: string;
  venueName?: string;
  venueAddress?: string;
  zoomLink?: string;
  liveStreamLink?: string;
  externalUrl?: string;
  ctaLabel?: string;
  ctaHref?: string;
  heroImageUrl?: string;
  imageAlt?: string;
  sortOrder: number;
  showOnHome?: boolean;
};

/** Church photos in apps/web/public/church/ (also used on home page). */
const IMG = {
  prayer: "/church/worship.jpg",
  worship: "/church/worship.jpg",
  bible: "/church/bible.webp",
  community: "/church/community.webp",
  missions: "/church/chicago.webp",
  family: "/church/community.webp",
  serve: "/church/serve.jpg",
  sundaySchool: "/church/sunday-school.jpg",
};

/**
 * Full ministry & service catalog — maps Pastor's 46-item vision to routes.
 * Items with canonicalPath link to existing pages (no duplicate URL).
 */
export const MINISTRY_SEEDS: MinistrySeed[] = [
  {
    _id: "ministry-give",
    slug: "donations",
    title: "Donations & giving",
    category: "connect",
    summary: "Support Lake Shore Church through tithes, offerings, missions, and building funds.",
    paragraphs: [
      "Your generosity fuels worship, discipleship, mercy, and missions in Chicago's West Loop and beyond. Lake Shore Church is a 501(c)(3) organization; gifts are tax-deductible where applicable.",
      "We use Zeffy for online giving (no platform fees to the church) and can also receive gifts through PayPal Giving Fund. Thank you for partnering with us in the gospel.",
    ],
    canonicalPath: "/give",
    ctaLabel: "Give now",
    ctaHref: "/give",
    sortOrder: 1,
    heroImageUrl: IMG.community,
    imageAlt: "Hands joined in fellowship",
  },
  {
    _id: "ministry-live",
    slug: "live-stream",
    title: "Live stream",
    category: "watch",
    summary: "Join Sunday worship and special gatherings online when you cannot be with us in person.",
    paragraphs: [
      "When we are live, watch on our Live page or YouTube. Wednesday prayer meetings also stream when announced — check the Weekly Gatherings section on the home page.",
      "Subscribe to notifications (browser or mobile app) so you do not miss go-live moments.",
    ],
    canonicalPath: "/live",
    liveStreamLink: "/live",
    ctaLabel: "Watch live",
    ctaHref: "/live",
    sortOrder: 2,
    showOnHome: true,
    heroImageUrl: IMG.worship,
    imageAlt: "Worship gathering",
  },
  {
    _id: "ministry-blog",
    slug: "blog",
    title: "Blog & articles",
    category: "watch",
    summary: "Teaching articles from Pastor Brian and the church — synced with Knowing God and His Ways.",
    paragraphs: [
      "Read devotionals and articles on our Blog. Pastor Brian also publishes at craigbrianlarson.com; selected posts are imported here so one church home stays current.",
    ],
    canonicalPath: "/blog",
    externalUrl: "https://craigbrianlarson.com/",
    ctaLabel: "Read the blog",
    ctaHref: "/blog",
    sortOrder: 3,
    heroImageUrl: IMG.bible,
    imageAlt: "Open Bible study",
  },
  {
    _id: "ministry-faq",
    slug: "faq",
    title: "FAQ",
    category: "church-life",
    summary: "Common questions about beliefs, visiting, giving, and getting involved.",
    paragraphs: [
      "See our dedicated FAQ page for answers about Assemblies of God beliefs, first-time visits, service times, and more.",
    ],
    canonicalPath: "/faq",
    ctaLabel: "View FAQ",
    ctaHref: "/faq",
    sortOrder: 4,
    heroImageUrl: IMG.community,
    imageAlt: "People in conversation",
  },
  {
    _id: "ministry-leaders",
    slug: "about-leaders",
    title: "About our leaders",
    category: "church-life",
    summary: "Meet Pastor Brian and the servant-leaders who shepherd Lake Shore Church.",
    paragraphs: [
      "Leadership at Lake Shore Church is rooted in scripture, prayer, and the gifts of the Holy Spirit. We serve as a family under Christ.",
    ],
    canonicalPath: "/about/leaders",
    ctaLabel: "Meet the leaders",
    ctaHref: "/about/leaders",
    sortOrder: 5,
    heroImageUrl: IMG.family,
    imageAlt: "Church leadership",
  },
  {
    _id: "ministry-beliefs",
    slug: "beliefs",
    title: "What we believe",
    category: "grow",
    summary: "Scripture-based, Assemblies of God theology — the gospel, the Spirit, and the hope of Christ's return.",
    paragraphs: [
      "We hold the Bible as God's inerrant Word, believe in the Trinity, salvation by grace through faith, baptism in water and the Holy Spirit, divine healing, and Christ's return.",
    ],
    canonicalPath: "/beliefs",
    ctaLabel: "Our beliefs",
    ctaHref: "/beliefs",
    sortOrder: 6,
    heroImageUrl: IMG.bible,
    imageAlt: "Scripture",
  },
  {
    _id: "ministry-visit",
    slug: "plan-your-visit",
    title: "Plan your visit",
    category: "connect",
    summary: "Sundays at 10 AM · Merit School of Music · West Loop Chicago. Everyone is welcome.",
    paragraphs: [
      "Doors open at 9:30 AM. Come as you are — we will help you find seating, children's ministry, and next steps in faith.",
    ],
    canonicalPath: "/visit",
    ctaLabel: "Plan a visit",
    ctaHref: "/visit",
    sortOrder: 7,
    showOnHome: true,
    heroImageUrl: IMG.community,
    imageAlt: "Welcoming church entrance",
  },
  {
    _id: "ministry-events",
    slug: "upcoming-events",
    title: "Upcoming events",
    category: "connect",
    summary: "Church-wide gatherings, outreaches, and special services.",
    paragraphs: ["Browse our calendar for what's ahead and add events to your personal calendar."],
    canonicalPath: "/events",
    ctaLabel: "See events",
    ctaHref: "/events",
    sortOrder: 8,
    heroImageUrl: IMG.community,
    imageAlt: "Community event",
  },
  {
    _id: "ministry-sermons",
    slug: "sermon-archives",
    title: "Sermon archives",
    category: "watch",
    summary: "Watch or listen to past messages from Sunday services and special meetings.",
    paragraphs: [
      "Messages are organized by series and date. Pastor Brian's podcast feed is also linked for audio on the go.",
    ],
    canonicalPath: "/sermons",
    externalUrl: "https://craigbrianlarson.libsyn.com/website",
    ctaLabel: "Sermon archive",
    ctaHref: "/sermons",
    sortOrder: 9,
    heroImageUrl: IMG.worship,
    imageAlt: "Preaching",
  },
  {
    _id: "ministry-prayer",
    slug: "prayer-requests",
    title: "Prayer requests",
    category: "connect",
    summary: "Share a need — our prayer team prays for every request.",
    paragraphs: [
      "Submit privately through our prayer form. A leader may follow up if you ask for contact.",
    ],
    canonicalPath: "/prayer",
    ctaLabel: "Request prayer",
    ctaHref: "/prayer",
    sortOrder: 10,
    showOnHome: true,
    heroImageUrl: IMG.prayer,
    imageAlt: "Praying together",
  },
  {
    _id: "ministry-testimonies",
    slug: "testimonies",
    title: "Testimonies",
    category: "church-life",
    summary: "Stories of salvation, healing, and God's faithfulness — in words, photos, audio, and video.",
    paragraphs: [
      "We celebrate what God is doing. Share your story with the church office to be featured (with your permission).",
    ],
    canonicalPath: "/testimonies",
    ctaLabel: "Read testimonies",
    ctaHref: "/testimonies",
    sortOrder: 11,
    heroImageUrl: IMG.family,
    imageAlt: "Sharing testimony",
  },
  {
    _id: "ministry-sunday-school",
    slug: "sunday-school",
    title: "Sunday school ministries",
    category: "connect",
    summary: "Bible teaching for children and adults before and alongside Sunday worship.",
    paragraphs: [
      "Classes meet on Sundays with age-appropriate curriculum rooted in scripture. Schedules and room assignments are posted at the welcome desk.",
      "Volunteer teachers serve through prayer and preparation — contact the church office to serve in children's or adult Sunday school.",
    ],
    scheduleLabel: "Sundays · before & during service",
    sortOrder: 12,
    heroImageUrl: IMG.sundaySchool,
    imageAlt: "Sunday school",
  },
  {
    _id: "ministry-wednesday-prayer",
    slug: "wednesday-prayer",
    title: "Wednesday prayer & fellowship",
    category: "connect",
    summary: "Mid-week prayer, worship, and shared meal in a home setting — also online via Zoom and live stream.",
    paragraphs: [
      "Wednesday gatherings strengthen our church family between Sundays. We pray for one another, the city, and the nations; share a meal; and often host the meeting in a member's home (address announced weekly).",
      "Join online when you cannot attend in person — Zoom link and live stream appear on the home page when active.",
    ],
    scheduleLabel: "Wednesdays · evening (CT)",
    scheduleDetails:
      "Host home, dinner, and exact start time are announced each week. Contact the church office for this week's address.",
    zoomLink: "",
    liveStreamLink: "/live",
    ctaLabel: "Request prayer",
    ctaHref: "/prayer",
    sortOrder: 13,
    showOnHome: true,
    heroImageUrl: IMG.prayer,
    imageAlt: "Wednesday prayer gathering",
  },
  {
    _id: "ministry-conferences",
    slug: "multi-conferences",
    title: "Online conferences & global connection",
    category: "missions",
    summary: "Special teaching gatherings to connect believers across time zones (coming soon).",
    paragraphs: [
      "We are planning periodic online conferences so friends worldwide can join Wednesday prayer rhythms and special teachings. Multilingual support is on our roadmap.",
      "Subscribe to email updates on the home page to hear when the next conference opens.",
    ],
    sortOrder: 40,
    heroImageUrl: IMG.missions,
    imageAlt: "Global connection",
  },
  {
    _id: "ministry-home-churches",
    slug: "planting-home-churches",
    title: "Planting home churches",
    category: "missions",
    summary: "Equipping families to host gospel-centered gatherings around the world.",
    paragraphs: [
      "Lake Shore Church believes the local church is God's plan — in Chicago and in every city. We pray for and mentor home church planters who hold to scripture and Pentecostal practice.",
      "If you sense a call to plant, speak with Pastor Brian after a Sunday service or through Contact.",
    ],
    sortOrder: 41,
    heroImageUrl: IMG.missions,
    imageAlt: "Home fellowship",
  },
  {
    _id: "ministry-multilingual",
    slug: "multilingual-resources",
    title: "Books & sermons in many languages",
    category: "missions",
    summary: "Translating teaching so every nation can hear the gospel clearly.",
    paragraphs: [
      "We are building partnerships to translate sermons, books, and prophecies. Staff use the translations portal; published translations will appear here as they are approved.",
    ],
    canonicalPath: "/resources",
    sortOrder: 42,
    heroImageUrl: IMG.bible,
    imageAlt: "Languages and scripture",
  },
  {
    _id: "ministry-mens",
    slug: "mens-ministry",
    title: "Men's ministry",
    category: "serve",
    summary: "Brothers growing as disciples, husbands, fathers, and witnesses at work.",
    paragraphs: [
      "Men meet for prayer, accountability, and practical teaching on walking honestly before God in family and workplace.",
    ],
    sortOrder: 20,
    heroImageUrl: IMG.serve,
    imageAlt: "Men's fellowship",
  },
  {
    _id: "ministry-womens",
    slug: "womens-ministry",
    title: "Women's ministry",
    category: "serve",
    summary: "Sisters encouraging one another in prayer, scripture, and everyday witness.",
    paragraphs: [
      "Women gather to study the Word, intercede, and share Christ in neighborhoods, workplaces, and gyms — like the simple ministers stories we celebrate on our Testimonies page.",
    ],
    sortOrder: 21,
    heroImageUrl: IMG.family,
    imageAlt: "Women's fellowship",
  },
  {
    _id: "ministry-worship-team",
    slug: "worship-team",
    title: "Worship team",
    category: "watch",
    summary: "Musicians and vocalists leading the church to encounter God in spirit and truth.",
    paragraphs: [
      "Our worship team prepares weekly for Sunday and special services. Rehearsals and set lists are coordinated with pastoral leadership.",
      "Watch recent worship moments on our Live and Sermons pages. To audition, contact the worship leader through the church office.",
    ],
    sortOrder: 14,
    heroImageUrl: IMG.worship,
    imageAlt: "Worship team",
  },
  {
    _id: "ministry-coffee-pastor",
    slug: "coffee-with-pastor",
    title: "Coffee with Pastor",
    category: "connect",
    summary: "Schedule a conversation with Pastor Brian — questions, counsel, or encouragement.",
    paragraphs: [
      "Pastor Brian makes time for one-on-one and small-group conversations. Use our Contact form with the subject \"Coffee with Pastor\" and your availability; the office will confirm a time.",
      "Online video visits are available when needed. For urgent pastoral care, call the church phone listed on the Contact page.",
    ],
    canonicalPath: "/contact",
    ctaLabel: "Request a meeting",
    ctaHref: "/contact",
    sortOrder: 15,
    heroImageUrl: IMG.community,
    imageAlt: "Conversation over coffee",
  },
  {
    _id: "ministry-holy-spirit",
    slug: "holy-spirit-baptism",
    title: "Baptism in the Holy Spirit",
    category: "grow",
    summary: "Teaching on the Spirit's fullness, tongues, and the gifts for the church today.",
    paragraphs: [
      "We believe the baptism in the Holy Spirit is available to all believers, with speaking in tongues as the initial physical evidence, and that the gifts of the Spirit continue for the building up of the body.",
      "Pastor Brian teaches regularly from scripture on yielding to the Spirit. Ask for prayer after any service — leaders will gladly pray with you.",
    ],
    canonicalPath: "/beliefs",
    ctaLabel: "Our beliefs",
    ctaHref: "/beliefs",
    sortOrder: 16,
    heroImageUrl: IMG.worship,
    imageAlt: "Worship in the Spirit",
  },
  {
    _id: "ministry-get-involved",
    slug: "get-involved",
    title: "Get involved in ministry",
    category: "serve",
    summary: "Serve as Levites, intercessors, musicians, technologists, hospitality, and more.",
    paragraphs: [
      "God gifts every believer for service. Tell us your interests — prayer team, music, media, children's ministry, hospitality, finance, or outreach — and we will connect you with a leader.",
    ],
    ctaLabel: "Volunteer interest",
    ctaHref: "/contact",
    sortOrder: 17,
    showOnHome: true,
    heroImageUrl: IMG.serve,
    imageAlt: "Serving together",
  },
  {
    _id: "ministry-radio",
    slug: "radio-ministry",
    title: "Radio ministry",
    category: "watch",
    summary: "Broadcasting hope through radio partners (schedule coming soon).",
    paragraphs: [
      "Short teachings and testimonies air through partner stations. Details and airtimes will be posted here as partnerships are confirmed.",
    ],
    sortOrder: 30,
    heroImageUrl: IMG.worship,
    imageAlt: "Radio broadcast",
  },
  {
    _id: "ministry-podcasts",
    slug: "podcasts",
    title: "Podcasts",
    category: "watch",
    summary: "Knowing God and His Ways — audio teaching from Pastor Brian.",
    paragraphs: [
      "Subscribe on Libsyn or your favorite podcast app. Episodes complement Sunday messages and daily devotionals on the blog.",
    ],
    externalUrl: "https://craigbrianlarson.libsyn.com/website",
    ctaLabel: "Open podcast",
    ctaHref: "https://craigbrianlarson.libsyn.com/website",
    sortOrder: 18,
    heroImageUrl: IMG.bible,
    imageAlt: "Podcast listening",
  },
  {
    _id: "ministry-cooking",
    slug: "cooking-ministry",
    title: "Cooking & potluck ministry",
    category: "connect",
    summary: "Shared meals on Sundays and at special gatherings — breaking bread as family.",
    paragraphs: [
      "On selected Sundays we enjoy potluck fellowship after service. Sign up to bring a dish or help with setup through the church office.",
    ],
    sortOrder: 22,
    heroImageUrl: IMG.family,
    imageAlt: "Shared meal",
  },
  {
    _id: "ministry-home-visit",
    slug: "pastor-home-visit",
    title: "Pastor or prayer team home visit",
    category: "connect",
    summary: "Request a pastoral or prayer visit in your home.",
    paragraphs: [
      "For hospital, homebound, or special pastoral needs, submit a prayer request or contact the church with your address and preferred times.",
    ],
    canonicalPath: "/prayer",
    ctaLabel: "Request a visit",
    ctaHref: "/prayer",
    sortOrder: 23,
    heroImageUrl: IMG.family,
    imageAlt: "Home visit",
  },
  {
    _id: "ministry-join-prayers",
    slug: "join-our-prayers",
    title: "Join our prayers",
    category: "connect",
    summary: "Saturday evening and Sunday morning prayer before services.",
    paragraphs: [
      "Saturday evening: intercession for Sunday worship. Sunday morning: prayer in the sanctuary before doors open at 9:30 AM. All are welcome — come early and seek God with us.",
    ],
    scheduleLabel: "Saturday evening & Sunday 9:30 AM",
    sortOrder: 24,
    showOnHome: true,
    heroImageUrl: IMG.prayer,
    imageAlt: "Corporate prayer",
  },
  {
    _id: "ministry-levites",
    slug: "levites",
    title: "Levites ministry",
    category: "serve",
    summary: "Serving in worship, order, and practical care of the house of God.",
    paragraphs: [
      "The Levites team supports Sunday flow — ushers, setup, communion prep, and altar ministry coordination. Training is provided.",
    ],
    sortOrder: 25,
    heroImageUrl: IMG.serve,
    imageAlt: "Serving in church",
  },
  {
    _id: "ministry-technology",
    slug: "technology-team",
    title: "Technology team",
    category: "serve",
    summary: "Live stream, sound, slides, and digital tools for in-person and online church.",
    paragraphs: [
      "Technologists and creatives serve behind the scenes so the gospel is heard clearly on Sunday and Wednesday. Experience with audio, video, or ProPresenter is welcome — willing hearts are essential.",
    ],
    sortOrder: 26,
    heroImageUrl: IMG.serve,
    imageAlt: "Media ministry",
  },
  {
    _id: "ministry-admin",
    slug: "admin-staff",
    title: "Administration & finance",
    category: "church-life",
    summary: "Stewardship of records, facilities, and transparent church finances.",
    paragraphs: [
      "Authorized staff and volunteers handle bookkeeping, Zeffy reconciliation, and facility coordination. Financial summaries are reviewed by church leadership.",
    ],
    sortOrder: 27,
    heroImageUrl: IMG.community,
    imageAlt: "Administration",
  },
  {
    _id: "ministry-new-believers",
    slug: "new-believers",
    title: "Bible basics for new believers",
    category: "grow",
    summary: "Starting your walk with Jesus — salvation, baptism, and the Holy Spirit.",
    paragraphs: [
      "If you are new to faith or preparing to follow Christ, begin with the gospel: God loves you; sin separates; Jesus died and rose; repent and believe.",
      "Next steps: water baptism, baptism in the Holy Spirit, join a local church, and read the Bible daily. Our Dedication page walks through these steps with scripture links.",
    ],
    canonicalPath: "/dedication",
    ctaLabel: "Start here",
    ctaHref: "/dedication",
    sortOrder: 19,
    heroImageUrl: IMG.bible,
    imageAlt: "New believer study",
  },
  {
    _id: "ministry-water-baptism",
    slug: "water-baptism-testimonies",
    title: "Water baptism testimonies",
    category: "church-life",
    summary: "Stories from those who have publicly declared faith in Christ through baptism.",
    paragraphs: [
      "We rejoice with every baptism. Testimonies are shared on baptism Sundays and collected on our Testimonies hub.",
    ],
    canonicalPath: "/testimonies",
    ctaLabel: "Read testimonies",
    ctaHref: "/testimonies",
    sortOrder: 28,
    heroImageUrl: IMG.worship,
    imageAlt: "Baptism",
  },
  {
    _id: "ministry-personal-dev",
    slug: "personal-development",
    title: "Personal development in Christ",
    category: "grow",
    summary: "Life dedication, daily walk with the Spirit, honest work, prayer, and readiness for Christ's return.",
    paragraphs: [
      "Discipleship is everyday obedience: private prayer, scripture memory, integrity at work, generosity, and longing for Jesus' return.",
      "Join a small group, attend Sunday school, and use Pastor Brian's blog and podcast for steady teaching.",
    ],
    sortOrder: 29,
    heroImageUrl: IMG.bible,
    imageAlt: "Personal devotion",
  },
  {
    _id: "ministry-tracks",
    slug: "street-ministry",
    title: "Tracks — street ministry",
    category: "missions",
    summary: "Taking the gospel to streets, events, and public spaces in Chicago.",
    paragraphs: [
      "Teams go out with prayer, literature, and invitations to church. Training emphasizes love, respect, and bold witness.",
    ],
    sortOrder: 31,
    heroImageUrl: IMG.missions,
    imageAlt: "Street outreach",
  },
  {
    _id: "ministry-god-test",
    slug: "god-test",
    title: "God test",
    category: "grow",
    summary: "A simple tool to explore what you believe about God (interactive — coming soon).",
    paragraphs: [
      "We are preparing a short questionnaire to help seekers reflect on creation, conscience, scripture, and Christ. Until then, read our Beliefs page or speak with a leader on Sunday.",
    ],
    canonicalPath: "/beliefs",
    sortOrder: 32,
    heroImageUrl: IMG.bible,
    imageAlt: "Reflection",
  },
  {
    _id: "ministry-bible-assistant",
    slug: "bible-theology-assistant",
    title: "Bible & theology assistant",
    category: "grow",
    summary: "Scripture-grounded help with Pentecostal doctrine (pilot planned).",
    paragraphs: [
      "A guarded Bible study assistant — aligned with Assemblies of God teaching — is in development for members. It will not replace pastoral counsel or the local church.",
    ],
    sortOrder: 43,
    heroImageUrl: IMG.bible,
    imageAlt: "Bible study technology",
  },
  {
    _id: "ministry-heaven-hell",
    slug: "heaven-and-hell",
    title: "Heaven & hell — biblical reality",
    category: "grow",
    summary: "Eternal life with God and the sober warning of judgment apart from Christ.",
    paragraphs: [
      "Scripture teaches eternal conscious fellowship with God for the redeemed and separation for those who reject Christ. We preach hope in the gospel and urgency in evangelism.",
    ],
    canonicalPath: "/beliefs",
    sortOrder: 33,
    heroImageUrl: IMG.bible,
    imageAlt: "Eternal hope",
  },
  {
    _id: "ministry-missionaries",
    slug: "missionaries",
    title: "Missionaries we support",
    category: "missions",
    summary: "Five missionary families and ministries partnered with Lake Shore Church.",
    paragraphs: [
      "We tithe into the nations through missionaries we know and pray for regularly. Profiles, countries, and giving designations will be listed here as updates are provided.",
      "Give to Missions on our Give page and note the family name in your gift memo when prompted.",
    ],
    canonicalPath: "/give",
    ctaLabel: "Give to missions",
    ctaHref: "/give",
    sortOrder: 34,
    heroImageUrl: IMG.missions,
    imageAlt: "Global missions",
  },
  {
    _id: "ministry-simple-ministers",
    slug: "simple-ministers",
    title: "Simple ministers of God",
    category: "church-life",
    summary: "Everyday witnesses — at work, the gym, and the neighborhood.",
    paragraphs: [
      "Ministry is not only on the platform. We celebrate members who wear faith boldly (like a \"Jesus loves you\" shirt), share Christ with coworkers, and invite friends to church.",
      "Tell us your story on the Testimonies page.",
    ],
    canonicalPath: "/testimonies",
    sortOrder: 35,
    heroImageUrl: IMG.family,
    imageAlt: "Everyday witness",
  },
  {
    _id: "ministry-pillars",
    slug: "church-pillars",
    title: "Pillars & early days",
    category: "church-life",
    summary: "How Lake Shore Church was established in the West Loop.",
    paragraphs: [
      "From small beginnings in prayer to a growing family in Chicago, God has been faithful. Founding stories and photos are being collected for this page — if you were part of our early days, contact the office.",
    ],
    canonicalPath: "/about",
    ctaLabel: "About us",
    ctaHref: "/about",
    sortOrder: 36,
    heroImageUrl: IMG.community,
    imageAlt: "Church history",
  },
  {
    _id: "ministry-membership",
    slug: "church-membership",
    title: "Becoming a member",
    category: "church-life",
    summary: "Covenant membership in a local body of believers.",
    paragraphs: [
      "Membership classes cover beliefs, vision, and expectations. Members commit to worship, give, serve, and live in accountability.",
      "Speak with Pastor Brian or an elder after Sunday service to begin.",
    ],
    canonicalPath: "/visit",
    sortOrder: 37,
    heroImageUrl: IMG.family,
    imageAlt: "Church membership",
  },
  {
    _id: "ministry-pastor-life",
    slug: "life-of-pastor-brian",
    title: "Life of Pastor Brian",
    category: "church-life",
    summary: "Biography, books, and teaching ministry of Craig Brian Larson.",
    paragraphs: [
      "Pastor Brian has served Lake Shore Church with a focus on expository preaching and the work of the Holy Spirit. He writes and teaches through Knowing God and His Ways (blog and podcast).",
      "Read more on our About page and at craigbrianlarson.com.",
    ],
    canonicalPath: "/about#pastor",
    externalUrl: "https://craigbrianlarson.com/",
    ctaLabel: "About Pastor Brian",
    ctaHref: "/about#pastor",
    sortOrder: 38,
    heroImageUrl: IMG.bible,
    imageAlt: "Pastor teaching",
  },
  {
    _id: "ministry-prophecies",
    slug: "prophecies",
    title: "Sunday prophecies",
    category: "watch",
    summary: "Words given in services — archived with translations when available.",
    paragraphs: [
      "When prophecy is given in a Sunday service, staff may publish a summary or transcript here (with pastoral review). Multilingual translations use our staff translations workflow.",
    ],
    sortOrder: 39,
    heroImageUrl: IMG.worship,
    imageAlt: "Prophetic ministry",
  },
];

export function ministrySeedToDocument(seed: MinistrySeed) {
  return {
    _id: seed._id,
    _type: "ministryPage" as const,
    title: seed.title,
    slug: { _type: "slug" as const, current: seed.slug },
    category: seed.category,
    summary: seed.summary,
    body: paragraphsToBlocks(seed.paragraphs),
    canonicalPath: seed.canonicalPath,
    scheduleLabel: seed.scheduleLabel,
    scheduleDetails: seed.scheduleDetails,
    venueName: seed.venueName,
    venueAddress: seed.venueAddress,
    zoomLink: seed.zoomLink || undefined,
    liveStreamLink: seed.liveStreamLink,
    externalUrl: seed.externalUrl,
    ctaLabel: seed.ctaLabel,
    ctaHref: seed.ctaHref,
    heroImageUrl: seed.heroImageUrl,
    imageAlt: seed.imageAlt,
    sortOrder: seed.sortOrder,
    showOnHome: seed.showOnHome ?? false,
    status: "published" as const,
  };
}

export async function seedMinistryPages(): Promise<void> {
  const client = getSanityWriteClient();
  for (const seed of MINISTRY_SEEDS) {
    await client.createOrReplace(ministrySeedToDocument(seed));
  }
}
